// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UbecSolicitacoes.Data;

#nullable disable

namespace UbecSolicitacoes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819215750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UbecSolicitacoes.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Matricula = "2024001",
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Matricula = "2024002",
                            Nome = "Maria Oliveira"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Matricula = "2024003",
                            Nome = "Pedro Santos"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = false,
                            Matricula = "2024004",
                            Nome = "Ana Costa"
                        });
                });

            modelBuilder.Entity("UbecSolicitacoes.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PrazoLimite")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Solicitacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlunoId = 1,
                            CriadaEm = new DateTime(2026, 8, 19, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            PrazoLimite = new DateTime(2026, 8, 21, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            Status = "Pendente",
                            TipoDocumento = "Declaração de Matrícula"
                        },
                        new
                        {
                            Id = 2,
                            AlunoId = 2,
                            CriadaEm = new DateTime(2026, 8, 15, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            PrazoLimite = new DateTime(2026, 8, 18, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            Status = "Pendente",
                            TipoDocumento = "Atestado de Frequência"
                        },
                        new
                        {
                            Id = 3,
                            AlunoId = 1,
                            CriadaEm = new DateTime(2026, 8, 14, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            PrazoLimite = new DateTime(2026, 8, 19, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            Status = "Concluída",
                            TipoDocumento = "Histórico Escolar"
                        },
                        new
                        {
                            Id = 4,
                            AlunoId = 3,
                            CriadaEm = new DateTime(2026, 8, 14, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            PrazoLimite = new DateTime(2026, 8, 16, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            Status = "Pendente",
                            TipoDocumento = "Declaração de Matrícula"
                        },
                        new
                        {
                            Id = 5,
                            AlunoId = 2,
                            CriadaEm = new DateTime(2026, 8, 19, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            PrazoLimite = new DateTime(2026, 8, 24, 18, 57, 47, 554, DateTimeKind.Local).AddTicks(3021),
                            Status = "Cancelada",
                            TipoDocumento = "Histórico Escolar"
                        });
                });

            modelBuilder.Entity("UbecSolicitacoes.Models.Solicitacao", b =>
                {
                    b.HasOne("UbecSolicitacoes.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
